# Generated by Django 4.1.3 on 2024-06-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customer_delete_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to='excel_files/'),
        ),
    ]
