# Generated by Django 4.1.3 on 2024-06-13 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customer_excel_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='excel_file',
        ),
    ]
